/**
 * PR7 — `openconnectors diagnose <connector>` command.
 *
 * Offline-safe helper that ALWAYS writes to `~/.openconnectors/diagnostics/`
 * (never next to the YAML). Two modes:
 *
 *   - default:    writes `<id>.diagnose.json` with a metadata stub.
 *                 Future work adds ARIA-snapshot capture via Playwright MCP;
 *                 for now the stub is a deterministic, PII-free scaffold so
 *                 downstream tooling has a stable file path.
 *
 *   - --scaffold: additionally writes `<id>.skeleton.yaml`, a loadable v1
 *                 connector skeleton (auth + one fetch action) the
 *                 contributor can edit.
 *
 * The output is PII-scrubbed by construction: every field is either
 * connector YAML metadata (already PII-free) or a fixed string.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { ConnectorLoader } from "../lib/connector-loader.js";
import { assertNoPii } from "../lib/learning.js";

export interface DiagnoseOptions {
  scaffold?: boolean;
  /** Override output directory (tests). Defaults to `~/.openconnectors/diagnostics`. */
  outDir?: string;
}

export function diagnosticsDir(override?: string): string {
  return override ?? join(homedir(), ".openconnectors", "diagnostics");
}

export interface DiagnoseResult {
  diagnose_path: string;
  scaffold_path?: string;
}

/**
 * Scaffold content for `<id>.skeleton.yaml`. Deliberately minimal: auth +
 * one fetch action with a single navigate step. It schema-validates under
 * the v1 loader.
 */
function skeletonYaml(id: string): string {
  return `# Generated by \`openconnectors diagnose --scaffold\`. Edit freely.
id: ${id}
name: "TODO: connector display name"
description: "TODO: one-line description"
version: 0.1.0
author: "TODO"
license: "MIT"
tags: []

institution:
  name: "TODO"
  url: "https://example.com"
  country: "IL"
  locale: "en-US"
  timezone: "UTC"

auth:
  type: credentials
  credentials:
    - key: username
      label: "Username"
      type: text
    - key: password
      label: "Password"
      type: password

actions:
  - name: list_items
    description: "TODO: what this action fetches"
    kind: fetch
    input_schema:
      type: object
      properties: {}
    output_schema: "TODO"
    steps:
      - phase: login
        instructions: |
          TODO: describe how to log in using {{username}} and {{password}}.
      - phase: extract
        instructions: |
          TODO: describe how to extract the data.
`;
}

/**
 * Build the diagnose JSON payload. Kept as a pure function so tests can
 * verify its shape without touching the filesystem.
 */
export function buildDiagnosePayload(
  id: string,
  version: string,
  actionNames: string[]
): Record<string, unknown> {
  return {
    connector_id: id,
    connector_version: version,
    generated_at: new Date().toISOString(),
    actions: actionNames,
    // Future: aria_snapshot, candidate_selectors, breadcrumbs go here.
    aria_snapshot: null,
    candidate_selectors: [],
    notes:
      "Run the Playwright MCP-driven snapshot step to populate aria_snapshot and candidate_selectors.",
  };
}

export async function diagnoseCommand(
  connectorId: string,
  opts: DiagnoseOptions = {}
): Promise<DiagnoseResult> {
  const loader = new ConnectorLoader();
  const loaded = await loader.get(connectorId);

  const payload = buildDiagnosePayload(
    loaded.connector.id,
    loaded.connector.version,
    loaded.connector.actions.map((a) => a.name)
  );

  // PII scrub: wrap the payload as a quirk and scan. This re-uses the same
  // guard we trust for `.learned.json` writes. Any future snapshot content
  // must survive this check.
  assertNoPii({ kind: "quirk", text: JSON.stringify(payload) });

  const dir = diagnosticsDir(opts.outDir);
  mkdirSync(dir, { recursive: true });
  const diagnosePath = join(dir, `${connectorId}.diagnose.json`);
  writeFileSync(diagnosePath, JSON.stringify(payload, null, 2), "utf-8");

  const result: DiagnoseResult = { diagnose_path: diagnosePath };
  if (opts.scaffold) {
    const scaffoldPath = join(dir, `${connectorId}.skeleton.yaml`);
    writeFileSync(scaffoldPath, skeletonYaml(connectorId), "utf-8");
    result.scaffold_path = scaffoldPath;
  }
  return result;
}
